Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -38,17 +38,17 @@ jobs:
         env:
           NEWRELIC_API_KEY: ${{ secrets.NEWRELIC_API_KEY }}
 
-        # Run a terraform fmt to check syntax
-      - name: Terraform Format
-        id: fmt
-        run: terraform fmt -check
+    #     # Run a terraform fmt to check syntax
+    #   - name: Terraform Format
+    #     id: fmt
+    #     run: terraform fmt -check
 
-        # Run a terraform validate
-      - name: Terraform Validate
-        id: validate
-    # Run even if formatting fails
-        if: success() || failure()
-        run: terraform validate -no-color
+    #     # Run a terraform validate
+    #   - name: Terraform Validate
+    #     id: validate
+    # # Run even if formatting fails
+    #     if: success() || failure()
+    #     run: terraform validate -no-color
 
       - name: Terraform Plan
         run: terraform plan
